#!/bin/bash
set -e

if ! aws --version >/dev/null 2>&1; then
    echo "You need to install the AWS CLI tools first."
    exit 1
fi

if [[ $(aws configure get region) != us-east-1 ]]; then
    echo "You must configure aws to use the us-east-1 region,"
    echo "to avoid incurring significant charges for S3 data transfer."
    exit 1
fi

echo "Enter a (unique-to-you) name for your Cloudformation stack."
echo "It can include letters (A-Z and a-z), numbers (0-9), and dashes (-)."
echo "For example, you could use: rapidtide-cfn-$(( $RANDOM % 100 + 1 ))"
read -e -p "Stack name: " CFNSTACK

echo -e "\nEnter the name of the S3 bucket you've created for your output data."
read -e -p "Bucket name: " OUTPUT_BUCKET

# fail and exit if we cannot read it
aws s3 ls $OUTPUT_BUCKET > /dev/null

# so far we only support hcp-openaccess and local
echo "Only hcp-openaccess and local storage are supported for input sources."
PS3="Select input source: "
INPUT_CHOICES=("hcp-openaccess" "local")
select INPUT_BUCKET in "${INPUT_CHOICES[@]}"; do
    case $INPUT_BUCKET in
        "hcp-openaccess")
            echo -e "\nEnter the AWS Access Key ID you were given for $INPUT_BUCKET."
            echo "This is NOT your own AWS credentials."
            read -e -p "Access Key ID: " IBKEY
            read -e -p "Access Key Secret: " IBSEC

            # fail and exit if we cannot read the input bucket with those credentials
            AWS_SESSION_TOKEN= AWS_ACCESS_KEY_ID=$IBKEY AWS_SECRET_ACCESS_KEY=$IBSEC \
                aws s3 ls $INPUT_BUCKET > /dev/null
            break
            ;;
        "local")
            echo "Using local storage."
            break
            ;;
        *) echo "Invalid option $REPLY";;
    esac
done


export AWS_PAGER=
aws cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --template-body "file:///$PWD/rapidtide-cloud.yaml" \
    --stack-name $CFNSTACK \
    --parameters ParameterKey=OutputBucket,ParameterValue=$OUTPUT_BUCKET \
                 ParameterKey=InputBucket,ParameterValue=$INPUT_BUCKET
echo $CFNSTACK > your-stack-name.txt
echo "Creating your stack: $CFNSTACK"
echo "Waiting for completion, this will take several minutes."
aws cloudformation wait stack-create-complete --stack-name $CFNSTACK

if [[ "$INPUT_BUCKET" != "local" ]]; then
    echo "Applying secret."
    SECRETARN=$(aws cloudformation describe-stack-resources --stack-name $CFNSTACK \
                | grep secret | cut -d'"' -f4)
    aws secretsmanager update-secret \
        --secret-id $SECRETARN \
        --description "The user's $INPUT_BUCKET credentials." \
        --secret-string "$IBKEY:$IBSEC"
fi

echo "Done creating $CFNSTACK."

