#!/bin/bash
set -euo pipefail

if [[ $# -ne 2 || ! ( $1 == "create" || $1 == "delete" ) ]] ; then
    echo "Usage: $0 [create|delete] stackname"
    exit 1
fi

CMD=$1
STACK=$2

if [ $CMD == "create" ]; then
    RUN="create-stack --capabilities CAPABILITY_IAM --template-body file:///$PWD/rapidtide-cloud.yaml"
    WAIT="stack-create-complete"
elif [ $CMD == "delete" ]; then
    RUN="delete-stack"
    WAIT="stack-delete-complete"
fi

export AWS_PAGER=
aws cloudformation $RUN --stack-name $STACK
echo "Waiting for $CMD completion, this will take several minutes."
echo "You may Control-c if you don't want to wait; this will not stop the task."
aws cloudformation wait $WAIT --stack-name $STACK
echo "Done."
if [ $CMD == "delete" ]; then
    echo "Note: If $STACK is not found the delete will have completed in just a few seconds."
fi
