#!/bin/bash
set -e

echo "Enter a (unique-to-you) name for your Cloudformation stack."
echo "It can include letters (A-Z and a-z), numbers (0-9), and dashes (-)."
echo "For example, you could use: rapidtide-cfn-$(( $RANDOM % 100 + 1 ))"
read -e -p "Stack name: " CFNSTACK

echo -e "\nEnter the name of the S3 bucket you've created for your output data."
read -e -p "Bucket name: " S3OUTBUCKET

# fail and exit if we cannot read it
aws s3 ls $S3OUTBUCKET > /dev/null

echo -e "\nEnter the AWS Access Key ID you were given for hcp-openaccess."
echo "This is NOT your own AWS credentials."
read -e -p "Access Key ID: " HCPKEY
read -e -p "Access Key Secret: " HCPSEC

# fail and exit if we cannot read hcp-openaccess with those credentials
AWS_ACCESS_KEY_ID=$HCPKEY AWS_SECRET_ACCESS_KEY=$HCPSEC \
    aws s3 ls hcp-openaccess > /dev/null

export AWS_PAGER=
aws cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --template-body "file:///$PWD/rapidtide-cloud.yaml" \
    --stack-name $CFNSTACK \
    --parameters ParameterKey=OutputBucket,ParameterValue=$S3OUTBUCKET
echo $CFNSTACK > your-stack-name.txt
echo "Creating your stack: $CFNSTACK"
echo "Waiting for completion, this will take several minutes."
aws cloudformation wait stack-create-complete --stack-name $CFNSTACK

echo "Applying secret."
SECRETARN=$(aws cloudformation describe-stack-resources --stack-name $CFNSTACK \
            | grep secret | cut -d'"' -f4)
aws secretsmanager update-secret \
    --secret-id $SECRETARN \
    --description "The user's HCP Openaccess credentials." \
    --secret-string "$HCPKEY:$HCPSEC"

echo "Done creating $CFNSTACK."

