#!/bin/bash
set -e

NOW=$(date +%s)
CFNSTACK=rapidtide-cfn-$NOW
if [[ "${BASH_VERSINFO:-0}" -ge 4 ]]; then
    echo "Enter a name for your Cloudformation stack or use this default."
    ADDLARG="-i $CFNSTACK"
else
    echo "Enter a name for your Cloudformation stack."
    echo "For example, you could use: $CFNSTACK"
fi
echo "It can include letters (A-Z and a-z), numbers (0-9), and dashes (-)."
read -e $ADDLARG -p "Stack name: " CFNSTACK

echo -e "\nEnter the name of the S3 bucket you've created for your output data."
read -e -p "Bucket name: " S3OUTBUCKET

# fail and exit if we cannot read it
aws s3 ls $S3OUTBUCKET > /dev/null

echo -e "\nEnter the AWS Access Key ID you were given for hcp-openaccess."
echo "This is NOT your own AWS credentials."
read -e -p "Access Key ID: " HCPKEY
read -e -p "Access Key Secret: " HCPSEC

# fail and exit if we cannot read hcp-openaccess with those credentials
AWS_ACCESS_KEY_ID=$HCPKEY AWS_SECRET_ACCESS_KEY=$HCPSEC \
    aws s3 ls hcp-openaccess > /dev/null

SECRETARN=$(
    aws secretsmanager create-secret \
    --name HCP_OPENACCESS_$NOW \
    --secret-string "$HCPKEY:$HCPSEC" \
    | grep ARN | cut -d '"' -f4 )

export AWS_PAGER=
aws cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --template-body file:///$PWD/rapidtide-cloud.yaml \
    --stack-name $CFNSTACK \
    --parameters \
      ParameterKey=OutputBucket,ParameterValue=$S3OUTBUCKET \
      ParameterKey=HcpOpenaccessSecret,ParameterValue=$SECRETARN

echo "Waiting for completion, this will take several minutes."
echo "You may Control-c if you don't want to wait; this will not stop the task."
aws cloudformation wait stack-create-complete --stack-name $CFNSTACK
echo "Done."

