#!/bin/bash
set -e

read -e -p "Stack to delete: " CFNSTACK
aws cloudformation describe-stacks --stack-name=$CFNSTACK > /dev/null
aws cloudformation delete-stack --stack-name $CFNSTACK
echo "Delete started."
