#!/bin/bash
set -e

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --jobname|-j) JOBNAME="$2"; shift ;;
        --arraysize|-a) ARRAYSIZE="$2"; shift ;;
        --command|-c) COMMAND="$2"; shift ;;
        --participant|-p) PARTICIPANT="$2"; shift;;
        --stack|-s) STACK="$2"; shift;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

QUEDEF=$(./batch-stack-info ${STACK:-$(cat your-stack-name.txt)})

echo $QUEDEF

if [[ -z $JOBNAME ]]; then
    JOBNAME=$(gum input --prompt "Job name? " --placeholder "something to id your job")
fi

if [[ -z $ARRAYSIZE && -z $PARTICIPANT ]]; then
    if gum confirm "Is this an array job?"; then
        ARRAYSIZE=$(gum input --prompt "Array size? " \
                    --placeholder "usually equal to lines in participants.txt")
    fi
fi
if [[ -n $ARRAYSIZE ]]; then
    PARTICIPANT=ARRAY
fi

if [[ -z $PARTICIPANT ]]; then
    PARTICIPANT=$(gum input --prompt "Participant and session? " \
                  --placeholder "participant_session")
fi

if [[ -z $COMMAND ]]; then
    COMMAND=$(gum input --prompt "Command? " --value="/data_out/config/")
fi

RUNCMD="aws batch submit-job $QUEDEF --job-name $JOBNAME"
if [[ -n $ARRAYSIZE ]]; then
    RUNCMD+=" --array-properties size=$ARRAYSIZE"
fi
RUNCMD+=" --container-overrides command=bash,$COMMAND,$PARTICIPANT"

echo $RUNCMD
$RUNCMD
