#!/bin/bash
set -e

TMP=$(mktemp)
STACK=${1:-$(cat your-stack-name.txt)}
aws cloudformation list-stack-resources --stack-name $STACK > $TMP

echo --job-queue $(grep job-queue $TMP | cut -d'"' -f4) \
     --job-definition $(grep job-defin $TMP | cut -d'"' -f4)

\rm $TMP

