#!/bin/bash

# mount data output folder

S3FS_AUTH_METHOD=${S3FS_AUTH_METHOD:-iam_role}
if ! s3fs dmd-rapidtide-output /data_out ; then
    s3fs -o $S3FS_AUTH_METHOD dmd-rapidtide-output /data_out
fi

# retrieve credentials from AWS Secrets

s3fs -o passwd_file=<(
    aws secretsmanager get-secret-value \
    --region us-east-1 \
    --output text \
    --secret-id hcp-openaccess \
    | cut -d$'\t' -f4 \
    | jq -jr '.KEY,":",.SECRET'
) \
     hcp-openaccess /data_in

exec "$@"
