#!/bin/bash

# mount data output folder

if [ "$AWS_EXECUTION_ENV" == "AWS_ECS_EC2" ]; then
    # AWS Batch
    S3FS_AUTH_METHOD="-o ecs"
elif  $(curl -s -m 1 http://169.254.169.254/latest/dynamic/instance-identity/document | grep -q availabilityZone) ; then
    # EC2
    S3FS_AUTH_METHOD="-o iam_role"
else
    S3FS_AUTH_METHOD=""
fi

s3fs $S3FS_AUTH_METHOD dmd-rapidtide-output /data_out

# credentials injected from AWS Secrets in env variable

s3fs -o passwd_file=<( echo $HCP_OPENACCESS_SECRET ) \
     hcp-openaccess /data_in

for MOUNT in /data_in /data_out; do
    if ! findmnt -n -P -t fuse.s3fs $MOUNT ; then
        echo WARNING: $MOUNT is not correctly mounted
    fi
done

exec "$@"
