#!/bin/bash

# mount data output folder
# these will authenticate either via IAM or an included .passwd-s3fs
s3fs dmd-rapidtide-output /data_out

# retrieve credentials from AWS Secrets

s3fs -o passwd_file=<(
    aws secretsmanager get-secret-value \
    --region us-east-1 \
    --output text \
    --secret-id hcp-openaccess \
    | cut -d$'\t' -f4 \
    | jq -jr '.KEY,":",.SECRET'
) \
     hcp-openaccess /data_in

exec "$@"
