#!/bin/bash

PARTICIPANT=${1:-100307}
docker run --env-file ~/.aws -v $PWD/.passwd-s3fs:/home/rapidtide/.passwd-s3fs:ro \
--rm \
--security-opt apparmor:unconfined \
--device /dev/fuse \
--cap-add SYS_ADMIN \
-it \
rtpluss3 \
/simple-cp-test $PARTICIPANT
