#!/bin/bash

TARGET=${1:-100307}

ARRAY_ARGS=" "
if [[ $TARGET == ARRAY ]]; then
    ARRAY_ARGS=" --env PARTICIPANT_ARRAY_FILE=participants.txt --env AWS_BATCH_JOB_ARRAY_INDEX=1 "
fi
docker run \
    --env HCP_OPENACCESS_SECRET=$(aws secretsmanager get-secret-value --secret-id HCP_OPENACCESS --output text | cut -d$'\t' -f4 ) \
    --env OUTPUT_BUCKET=dmd-rapidtide-output \
    $ARRAY_ARGS \
    --env-file ~/.awsenv \
    --rm \
    --security-opt apparmor:unconfined \
    --device /dev/fuse \
    --cap-add SYS_ADMIN \
    -it \
    dmd3eorg/rapidtide-cloud \
    /simple-cp-test $TARGET
