#!/bin/bash

if [ ! $# -eq 1 ]; then
    echo participant id required
    exit 1
fi

P=$1

if [ "$P" == "ARRAY" ]; then
    P=$(/get-array-line /data_out/config/$PARTICIPANT_ARRAY_FILE)
fi

mkdir -p /data_out/HCP_1200/${P}
rapidtide \
            /data_in/HCP_1200/${P}/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz \
            /data_out/HCP_1200/${P}/rapidtide_rfMRI_REST1_LR \
            --filterband lfo \
            --searchrange -15 15 \
            --passes 2 \
            --nprocs -1 \
            --timerange 0 300
