#!/bin/bash

if [ ! $# -eq 1 ]; then
    echo participant id required
    exit 1
fi

mkdir -p /data_out/HCP_1200/${1}
rapidtide \
            /data_in/HCP_1200/${1}/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz \
            /data_out/HCP_1200/${1}/rapidtide_rfMRI_REST1_LR \
            --filterband lfo \
            --searchrange -15 15 \
            --passes 2 \
            --timerange 0 300
