#!/bin/bash

REPO="docker://public.ecr.aws/l0v4l2q2/rapidtide-cloud"
aws ecr-public get-login-password | skopeo login --username AWS --password-stdin public.ecr.aws/l0v4l2q2/rapidtide-cloud
skopeo copy --all docker://fredericklab/rapidtide-cloud $REPO
